# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "roboxes/ubuntu2004"
  config.ssh.insert_key = false
  config.vm.provider "hyperv"

  config.vm.provider :hyperv do |v|
    v.memory = 2048
    v.cpus = 1
    v.linked_clone = true
  end

  # Define three VMs with static private IP addresses.
  boxes = [
    { :name => "master", :ip => "192.168.56.2" },
    { :name => "worker1", :ip => "192.168.56.3" }
  ]

  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name] + ".k8s.test"
      config.vm.network :private_network, ip: opts[:ip]
    end
  end

end